In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

import warnings
warnings.filterwarnings('ignore')

In [2]:
forest_data = pd.read_csv('forestfires.csv')
forest_data

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         1         0   

     monthsep  size_category  
0           0          small  
1           0          small  
2           0          small  
3           0          small  
4           0          small  
..        ...            ...  
512         0          large  
513         0          large  
514         0          large  
515         0          small  
516         0          small  

[517 rows x 31 columns]

In [3]:
forest_data.shape

(517, 31)

In [4]:
forest_data.isna().sum()

month            0
day              0
FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [5]:
forest_data.dtypes

month             object
day               object
FFMC             float64
DMC              float64
DC               float64
ISI              float64
temp             float64
RH                 int64
wind             float64
rain             float64
area             float64
dayfri             int64
daymon             int64
daysat             int64
daysun             int64
daythu             int64
daytue             int64
daywed             int64
monthapr           int64
monthaug           int64
monthdec           int64
monthfeb           int64
monthjan           int64
monthjul           int64
monthjun           int64
monthmar           int64
monthmay           int64
monthnov           int64
monthoct           int64
monthsep           int64
size_category     object
dtype: object

### Data Preprocessing

In [6]:
forest_data.drop(labels='month',axis=1,inplace=True)
forest_data.drop(labels='day',axis=1,inplace=True)

In [7]:
x = forest_data.drop(labels='size_category',axis=1)
y = forest_data['size_category']

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [9]:
scaled_x = scaler.fit_transform(x)
scaled_x

array([[-8.05959472e-01, -1.32332557e+00, -1.83047676e+00, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [-8.10203395e-03, -1.17954077e+00,  4.88890915e-01, ...,
        -4.40225453e-02,  5.78503817e+00, -7.06081245e-01],
       [-8.10203395e-03, -1.04982188e+00,  5.60715454e-01, ...,
        -4.40225453e-02,  5.78503817e+00, -7.06081245e-01],
       ...,
       [-1.64008316e+00, -8.46647711e-01,  4.74768113e-01, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [ 6.80956663e-01,  5.49002541e-01,  2.69382214e-01, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [-2.02087875e+00, -1.68591332e+00, -1.78044169e+00, ...,
         2.27156334e+01, -1.72859706e-01, -7.06081245e-01]])

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
y_transform = le.fit_transform(y)

In [12]:
y_transform

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,

### Model Building

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(scaled_x,y_transform,test_size=0.20,random_state=12,stratify=y)

In [14]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((413, 28), (413,), (104, 28), (104,))

In [15]:
y_test

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

### Model Training

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,MaxPool2D

In [17]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_dim = 28), #I/player
                                    tf.keras.layers.Dense(25,activation = 'relu'), #Hidden layer 1
                                    tf.keras.layers.Dense(1,activation = 'sigmoid')]) #O/p layer

In [18]:
model.compile(optimizer ='RMSprop',loss= 'binary_crossentropy',metrics =['accuracy'])

In [19]:
model.fit(x_train,y_train,epochs=30)

Epoch 1/30
13/13 [==============================] - 0s 699us/step - loss: 0.7803 - accuracy: 0.4625
Epoch 2/30
13/13 [==============================] - 0s 499us/step - loss: 0.7110 - accuracy: 0.5400
Epoch 3/30
13/13 [==============================] - 0s 718us/step - loss: 0.6675 - accuracy: 0.5714
Epoch 4/30
13/13 [==============================] - 0s 552us/step - loss: 0.6345 - accuracy: 0.6174
Epoch 5/30
13/13 [==============================] - 0s 582us/step - loss: 0.6081 - accuracy: 0.6852
Epoch 6/30
13/13 [==============================] - 0s 582us/step - loss: 0.5872 - accuracy: 0.7337
Epoch 7/30
13/13 [==============================] - 0s 430us/step - loss: 0.5700 - accuracy: 0.7482
Epoch 8/30
13/13 [==============================] - 0s 748us/step - loss: 0.5561 - accuracy: 0.7530
Epoch 9/30
13/13 [==============================] - 0s 499us/step - loss: 0.5441 - accuracy: 0.7554
Epoch 10/30
13/13 [==============================] - 0s 665us/step - loss: 0.5333 - accuracy: 0.7579

In [20]:
model.evaluate(x_test,y_test)

4/4 [==============================] - 0s 1ms/step - loss: 0.6647 - accuracy: 0.7692


[0.6647399067878723, 0.7692307829856873]

In [21]:
y_pred = model.predict(x_test)
y_pred

array([[0.7173698 ],
       [0.79113275],
       [0.83457017],
       [0.55898726],
       [0.62065935],
       [0.83648545],
       [0.75657696],
       [0.6505307 ],
       [0.8103632 ],
       [0.8084955 ],
       [0.7260462 ],
       [0.7025281 ],
       [0.57579243],
       [0.76830435],
       [0.8863777 ],
       [0.62218815],
       [0.29992753],
       [0.7074513 ],
       [0.77712727],
       [0.8099953 ],
       [0.7480251 ],
       [0.7326113 ],
       [0.7346792 ],
       [0.8864705 ],
       [0.88726825],
       [0.75052965],
       [0.7728543 ],
       [0.67566776],
       [0.7039292 ],
       [0.8174008 ],
       [0.8536157 ],
       [0.6926029 ],
       [0.6582849 ],
       [0.6841647 ],
       [0.1952433 ],
       [0.80776614],
       [0.800248  ],
       [0.78568083],
       [0.9999995 ],
       [0.99016285],
       [0.719961  ],
       [0.9078935 ],
       [0.69071645],
       [0.8038701 ],
       [0.6845881 ],
       [0.7817545 ],
       [0.78782266],
       [0.197

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
pred=[]
for i in range(0,len(y_pred)):
    if y_pred[i]<0:
        y_pr=0
    else:
        y_pr=1
    pred.append(y_pr)

In [24]:
accuracy_score(y_test,pred)

0.7307692307692307